### ISSUE TITLE
Whether possible for multi-language support 

### ISSUE THREAD

**Issue by prozhong** [EnderWiggin/Custom-Salem#10]
Didn't mean any offence, its great to achieve multi-language support.
I know little about java, where does the client read the text data in this framework?

**Comment by EnderWiggin** [comment]
well, text is scattered in multiple places. Some of it is hard-coded in sources. Some in resources, and some even is sent directly from server.

**Comment by prozhong** [comment]
seems they didn't care about this when start salem.....

Its impossible to finish translation only by modifying one xml or json?

where does the text string on items (item name) exist ?That would help a lot if can be changed easily

**Comment by prozhong** [comment]
I had changed the salem-res.jar\res\paginae\act\adv.res\action data by using the "salem-layer-util-master" 


;ACTION Layer data file
;pr (string):

;pversion (uint-16):
0
;name (string):
Adventureffff
;prerequisite skill (ignored) (string):

;hk (uint-16):
118
;ad length (uint-16):
0


After encode I put *.res back in salem-res.jar, but the text in game didn't change...

(I cleared the java cache)
